#!/usr/bin/env python

import sys

alg = {}

for l in sys.stdin:
    l = l.rstrip()
    if l[0] == 'a':
        u, i, y = l[1:].split(',')
        i = int(i)
        if i == 0:
            assert u not in alg
            alg[u] = y
        else:
            assert u in alg
            len(alg[u]) == i
            alg[u] += y

for u in sorted(alg.keys()):
    print u, alg[u]
